apiVersion: v1
kind: ConfigMap
metadata:
  name: coyotefe-config
data:
  config.json: |
    {
      "VITE_S3_ENDPOINT": "/s3/",
      "VITE_DB_ENDPOINT": "/db/",
      "VITE_SQS_ENDPOINT": "/sqs/",
      "VITE_AWS_CLIENTID": "46f7p74qp752l43kgrlj8q29jg",
      "VITE_AWS_AUTHORITY": "https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_JNL3rksoP",
      "VITE_AWS_REDIRECTURI": "http://localhost:8080/",
      "VITE_AWS_COGNITODOMAIN": "https://eu-west-2jnl3rksop.auth.eu-west-2.amazoncognito.com"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coyotedb-config
data:
  PORT: "3001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coyotes3-config
data:
  AWS_REGION: "eu-west-2"
  PORT: "3002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coyotesqs-config
data:
  PORT: "3003"
  AWS_REGION: "eu-west-2"
  API_VERSION: "2012-11-05"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coyotefe-nginx-config
data:
  nginx.conf: |
    server {
      listen 8080;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      client_max_body_size 100M;
      location /db/ { proxy_pass http://coyotedb-service:3001/; }
      location /s3/ { proxy_pass http://coyotes3-service:3002/; }
      location /sqs/ { proxy_pass http://coyotesqs-service:3003/; }
      location / { try_files $uri $uri/ /index.html; }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coyotespeech-config
data:
  SQS_API: "http://coyotesqs-service:3003"
  S3_API: "http://coyotes3-service:3002"
  DB_HOST: "http://coyotedb-service:3001"
