apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotefrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotefrontend
  template:
    metadata:
      labels:
        app: coyotefrontend
    spec:
      containers:
        - name: frontend
          image: peterheywood708/coyotefrontend:main
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: config-js
              mountPath: /usr/share/nginx/html/config
              readOnly: true
            - name: config-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-js
          configMap:
            name: coyotefe-config
        - name: config-nginx
          configMap:
            name: coyotefe-nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotedb
  template:
    metadata:
      labels:
        app: coyotedb
    spec:
      containers:
        - name: db
          image: peterheywood708/coyotedb:main
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: coyotedb-config
                  key: PORT
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: external-secret-db
                  key: uri
            - name: COGNITO_USERPOOLID
              valueFrom:
                secretKeyRef:
                  name: external-secret-db
                  key: userpoolid
            - name: COGNITO_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: external-secret-db
                  key: clientid
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotes3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotes3
  template:
    metadata:
      labels:
        app: coyotes3
    spec:
      containers:
        - name: s3
          image: peterheywood708/coyotes3:main
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: coyotes3-config
                  key: PORT
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: coyotes3-config
                  key: AWS_REGION
            - name: S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: external-secret-s3
                  key: accesskey
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: external-secret-s3
                  key: secret
            - name: S3_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: external-secret-s3
                  key: bucketname
            - name: COGNITO_USERPOOLID
              valueFrom:
                secretKeyRef:
                  name: external-secret-s3
                  key: userpoolid
            - name: COGNITO_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: external-secret-s3
                  key: clientid
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotesqs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotesqs
  template:
    metadata:
      labels:
        app: coyotesqs
    spec:
      containers:
        - name: sqs
          image: peterheywood708/coyotesqs:main
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: coyotesqs-config
                  key: PORT
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: coyotesqs-config
                  key: AWS_REGION
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: coyotesqs-config
                  key: API_VERSION
            - name: COGNITO_USERPOOLID
              valueFrom:
                secretKeyRef:
                  name: external-secret-sqs
                  key: userpoolid
            - name: COGNITO_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: external-secret-sqs
                  key: clientid
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: external-secret-sqs
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: external-secret-sqs
                  key: secret
            - name: AWS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: external-secret-sqs
                  key: queue
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coyotespeech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coyotespeech
  template:
    metadata:
      labels:
        app: coyotespeech
    spec:
      containers:
        - name: speech
          image: peterheywood708/coyotespeech:main
          env:
            - name: SQS_API
              valueFrom:
                configMapKeyRef:
                  name: coyotespeech-config
                  key: SQS_API
            - name: S3_API
              valueFrom:
                configMapKeyRef:
                  name: coyotespeech-config
                  key: S3_API
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: coyotespeech-config
                  key: DB_HOST
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-secret-speech
                  key: token
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-secret-speech
                  key: openapikey
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcredy
