apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: external-secret-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/coyote/db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: external-secret-s3
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/coyote/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-sqs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: external-secret-sqs
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/coyote/sqs
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-speech
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: external-secret-speech
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/coyote/speech
