name: Terraform Plan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  plan:
    name: Terraform Plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Get directory
        run: ls"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{vars.AWS_REGION}}
          role-session-name: TerraformPlanSession
          role-skip-session-tagging: true

      - name: Terraform plan
        id: plan
        uses: dflook/terraform-plan@v1
        env:
          add_github_comment: changes-only
          TF_PLAN_COLLAPSE_LEVEL: 30

      - name: Terraform Plan Status
        if: steps.plan.outputs == 'failure'
        run: exit 1
